nodeLinker: node-modules

supportedArchitectures:
    cpu:
        - current
        - x64
        - ia32
        - arm64
    libc:
        - current
        - glibc
        - musl
    os:
        - current
        - darwin
        - linux
        - win32

yarnPath: .yarn/releases/yarn-4.0.2.cjs
